# Datos de trazabilidad SRS ↔ Sprint ↔ UC ↔ Implementación ↔ SAD

# (RF, nombre corto, UC, sprint, estado, referencia SAD)
TRAZABILIDAD_SPRINT = [
    ("RF-001", "Iniciar sesión", "UC-001", "1", "Implementado",
     "SAD §4.1 Acceso — Secuencia CU-001; Componentes Auth"),
    ("RF-002", "Gestionar usuarios y asignar rol", "UC-002", "2", "Implementado",
     "SAD §4.2 Administración — Secuencia CU-002; users.js"),
    ("RF-003", "Visualizar historial de acciones", "UC-003", "2", "Implementado",
     "SAD §4.2 Administración — Historial en Usuarios"),
    ("RF-004", "Registrar lote medicamento existente", "UC-008", "3", "Implementado",
     "SAD §4.3 Medicamentos — NuevoMedicamento.jsx"),
    ("RF-005", "Registrar medicamento nuevo con IA", "UC-007", "3", "Implementado",
     "SAD §4.3 Medicamentos — Búsqueda IA en registro"),
    ("RF-006", "Consultar medicamento", "UC-010", "3", "Implementado",
     "SAD §4.3 Medicamentos — Medicamentos.jsx"),
    ("RF-007", "Listar medicamentos", "UC-004", "3", "Implementado",
     "SAD §4.3 Medicamentos — medicamentos.js"),
    ("RF-008", "Filtrar listado de medicamentos", "UC-006", "4", "Implementado",
     "SAD §4.3 Medicamentos — Filtro laboratorio"),
    ("RF-009", "Modificar medicamento", "UC-009", "3", "Parcial",
     "SAD §4.3 Medicamentos — UI pendiente (botón Editar)"),
    ("RF-010", "Visualizar semáforo de stock", "UC-014", "4", "Implementado",
     "SAD §4.4 Inventario — ControlInventario.jsx"),
    ("RF-011", "Visualizar semáforo por vencer", "UC-012", "4", "Implementado",
     "SAD §4.4 Inventario — Pestaña por vencer"),
    ("RF-012", "Listar medicamentos con semáforo", "UC-015", "4", "Implementado",
     "SAD §4.4 Inventario — Tabla con badges de estado"),
    ("RF-013", "Filtrar lista de vencimientos", "UC-013", "4", "Implementado",
     "SAD §4.4 Inventario — Filtros de vencimiento"),
    ("RF-014", "Reporte general de medicamentos", "UC-016", "6", "Implementado",
     "SAD §4.5 Reportes — reportes.js; Reportes.jsx"),
    ("RF-015", "Reporte ingresos y salidas", "UC-017", "7", "Implementado",
     "SAD §4.5 Reportes — Movimientos semanales"),
    ("RF-016", "Reporte rotación de medicamentos", "UC-018", "7", "Implementado",
     "SAD §4.5 Reportes — Rotación"),
    ("RF-017", "Visualizar dashboard analítico", "UC-019, UC-020", "8", "Implementado",
     "SAD §4.6 Dashboard — dashboard.js; analytics.js"),
]

# (componente, tipo, ruta, RF, UC, capa SAD / paquete)
INVENTARIO_IMPLEMENTACION = [
    # Frontend
    ("React App (SPA)", "Frontend", "src/main.jsx, src/App.jsx", "RF-001–RF-017", "Todos",
     "SAD — Contenedor React + enrutamiento por estado"),
    ("Login", "Página", "src/pages/Login.jsx", "RF-001", "UC-001", "SAD — Acceso al Sistema"),
    ("AuthContext", "Contexto", "src/context/AuthContext.jsx", "RF-001", "UC-001", "SAD — Control de sesión"),
    ("Usuarios", "Página", "src/pages/Usuarios.jsx", "RF-002, RF-003", "UC-002, UC-003",
     "SAD — Administración de Usuarios"),
    ("Medicamentos", "Página", "src/pages/Medicamentos.jsx", "RF-006–RF-008", "UC-004, UC-006, UC-010",
     "SAD — Gestión de Medicamentos"),
    ("NuevoMedicamento", "Página", "src/pages/NuevoMedicamento.jsx", "RF-004, RF-005", "UC-007, UC-008",
     "SAD — Registro de medicamentos"),
    ("ControlInventario", "Página", "src/pages/ControlInventario.jsx", "RF-010–RF-013",
     "UC-012–UC-015", "SAD — Control de Inventario"),
    ("Notificaciones", "Página", "src/pages/Notificaciones.jsx", "—", "UC-011",
     "SAD — Alertas y Notificaciones"),
    ("Reportes", "Página", "src/pages/Reportes.jsx", "RF-014–RF-016", "UC-016–UC-018",
     "SAD — Reportes y Análisis"),
    ("Dashboard", "Página", "src/pages/Dashboard.jsx", "RF-017", "UC-019", "SAD — Dashboard Analítico"),
    ("Analytics", "Página", "src/pages/Analytics.jsx", "RF-017", "UC-020", "SAD — Dashboard Inteligente"),
    ("API Client", "Servicio", "src/services/api.js", "RF-001–RF-017", "Todos", "SAD — Capa de integración REST"),
    ("Sidebar", "Componente", "src/components/Sidebar.jsx", "RF-001", "UC-001", "SAD — Menú por rol"),
    # Backend
    ("Express App", "Backend", "backend/index.js", "RF-001–RF-017", "Todos", "SAD — API REST :3001"),
    ("auth.js / authController", "Ruta + Controlador", "backend/routes/auth.js, controllers/authController.js",
     "RF-001", "UC-001", "SAD — Autenticación"),
    ("users.js / userController", "Ruta + Controlador", "backend/routes/users.js, controllers/userController.js",
     "RF-002, RF-003", "UC-002, UC-003", "SAD — Usuarios e historial"),
    ("userModel", "Modelo", "backend/models/userModel.js", "RF-002", "UC-002", "SAD — Entidad Usuario"),
    ("medicamentos.js / medicamentoController", "Ruta + Controlador",
     "backend/routes/medicamentos.js, controllers/medicamentoController.js",
     "RF-004–RF-009", "UC-004–UC-010", "SAD — CRUD Medicamentos"),
    ("medicamentoModel", "Modelo", "backend/models/medicamentoModel.js", "RF-004–RF-009", "UC-004–UC-010",
     "SAD — Entidad Medicamento"),
    ("laboratorios (ruta)", "Ruta", "backend/routes/laboratorios.js", "RF-008", "UC-006", "SAD — Catálogo laboratorios"),
    ("inventario.js / inventarioController", "Ruta + Controlador",
     "backend/routes/inventario.js, controllers/inventarioController.js",
     "RF-010–RF-013", "UC-012–UC-015", "SAD — Control inventario"),
    ("inventarioModel", "Modelo", "backend/models/inventarioModel.js", "RF-010–RF-013", "UC-012–UC-015",
     "SAD — Consultas stock/vencimiento"),
    ("notificaciones.js", "Ruta + Controlador", "backend/routes/notificaciones.js, controllers/notificacionController.js",
     "—", "UC-011", "SAD — Bandeja de alertas"),
    ("notificacionModel", "Modelo", "backend/models/notificacionModel.js", "—", "UC-011", "SAD — Entidad Notificación"),
    ("reportes.js / reporteController", "Ruta + Controlador",
     "backend/routes/reportes.js, controllers/reporteController.js",
     "RF-014–RF-016", "UC-016–UC-018", "SAD — Reportes"),
    ("reporteModel", "Modelo", "backend/models/reporteModel.js", "RF-003, RF-014", "UC-003, UC-016",
     "SAD — Historial y resumen reportes"),
    ("dashboard.js / dashboardController", "Ruta + Controlador",
     "backend/routes/dashboard.js, controllers/dashboardController.js",
     "RF-017", "UC-019", "SAD — Dashboard operativo"),
    ("analytics.js / analyticsController", "Ruta + Controlador",
     "backend/routes/analytics.js, controllers/analyticsController.js",
     "RF-017", "UC-020", "SAD — Analytics ML/IA"),
    ("dashboardModel / analyticsModel", "Modelo", "backend/models/dashboardModel.js, analyticsModel.js",
     "RF-017", "UC-019, UC-020", "SAD — Datos analíticos"),
    # Datos
    ("MySQL — mopgimed", "Base de datos", "backend/db/connection.js, db/setup.js", "RF-001–RF-017", "Todos",
     "SAD — Persistencia (tablas users, medicamentos, notificaciones, etc.)"),
]
